---
title: Slow Factory Labs
timezone: America/New_York
future: true
permalink: pretty

collections:
  pages:
    title: Pages
    output: true
    permalink: "/:path"
  jobs:
    title: Jobs
    output: true

defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: jobs
  values:
    layout: jobs


include: [
  _pages
]
exclude: [
  README.md,
  firebase.json,
  gemfiles/,
  Gemfile,
  Gemfile.lock,
  node_modules/,
  package.json,
  postcss.config.js,
  webpack.config.js,
  webpack.config.babel.js,
  vendor/,
  vendor/bundle/,
  vendor/cache/,
  vendor/gems/,
  vendor/ruby/,
  yarn.lock
]
